### ISSUE TITLE
Http 404 error

### ISSUE THREAD

**Issue by peraugym** [trakt-for-plex/configuration#10]
Hi, After entering my plex user credentials I select my server but after a minute I get a 404error messenger. 
![bildschirmfoto 2015-10-24 um 20 10 36](https://cloud.githubusercontent.com/assets/15281205/10711976/32c600d2-7a8c-11e5-9657-2980700c5132.png)

**Comment by fuzeman** [comment]
The 404 error usually means the plugin isn't running the beta version of the plugin, could you check what version you have installed in Plex/Web at ```Channels -> trakt -> About```

**Comment by InteNs** [comment]
hey same issue, how would i go about installing that beta? manually copy the bundle to my plugins folder?

**Comment by fuzeman** [comment]
@InteNs 

1. *(optional) If you have installed the plugin via Unsupported AppStore, use the UAS channel to uninstall the current plugin (this ensures you won't continue getting stable channel updates)*
2. Download the latest beta release "Source code (zip)" from [here](https://github.com/trakt/Plex-Trakt-Scrobbler/releases)
3. Extract the zip archive
4. Move the ```Trakttv.bundle``` folder into your [plugins directory](https://support.plex.tv/hc/en-us/articles/201106098-How-do-I-find-the-Plug-Ins-folder-)

**Comment by peraugym** [comment]
It works with the trakt beta! 

What about users that do not have an additional account set up? Will they still scrobble with my primary account or not at all? Just wondering because I have removed th global filter by my plex username. 

Thanks!

**Comment by fuzeman** [comment]
@peraugym

If you do the "4. Setup rules" step in issue #1 additional accounts will be ignored if they don't have an account set up.
