### ISSUE TITLE
Unknown Error When picking server

### ISSUE THREAD

**Issue by EldonMcGuinness** [trakt-for-plex/configuration#12]
I get an error when trying to set this up at the second step when I try to pick my server, it just says "unknown error"

**Comment by fuzeman** [comment]
Could you do the following:

1. Navigate to the server selection page again (http://trakt-for-plex.github.io/configuration/#/connect)
2. Open the browser console (Ctrl+Shift+K on Firefox, Ctrl+Shift+J on Chrome)
3. Select your server
4. Screenshot the messages displayed in the browser console

Uploading the plugin log files might help as well, see https://github.com/fuzeman/Plex-Trakt-Scrobbler/wiki/Log-files for the location of them.

**Comment by EldonMcGuinness** [comment]
This was caused due to the plugin version being old, was still using a beta.

**Comment by almostserious** [comment]
I get an "authentification failed" error with 1.1.0.6

scripts.92aa1910.js:1 Connection successful
scripts.92aa1910.js:2 [6dff90964b3af65f2dad6f27a788322b658c2fa9] Request "system.authenticate" Object {args: Array[2], kwargs: undefined}
scripts.92aa1910.js:2 [6dff90964b3af65f2dad6f27a788322b658c2fa9] Response Object {error: Object}
scripts.92aa1910.js:1 Authentication failed
