### ISSUE TITLE
http://trakt-for-plex.github.io/configuration/#/connect hangs

### ISSUE THREAD

**Issue by tillmanj** [trakt-for-plex/configuration#13]
http://trakt-for-plex.github.io/configuration/#/connect never connects to Plex Server, despite having a fully accessible outside connection.

**Comment by fuzeman** [comment]
Could you do the following to help identify what is causing this:

1. Navigate to the server selection page again (http://trakt-for-plex.github.io/configuration/#/connect)
2. Open the browser console (Ctrl+Shift+K on Firefox, Ctrl+Shift+J on Chrome)
3. Select your server
4. Screenshot the messages displayed in the browser console

---------------

I think there might be some issues with connection timeouts, possibly being more noticeable on remote servers. Still need to work out the exact steps to reproduce this issue though.

**Comment by tillmanj** [comment]
![capture](https://cloud.githubusercontent.com/assets/8162037/13060516/0990befa-d400-11e5-81db-b701b9068aff.PNG)


Exposed root method "pins" vendor.859d191d.js:20:5395
plex initialized vendor.859d191d.js:20:13513
syntax error configuration:1:1
authenticated scripts.4ef01a59.js:1:2211
syntax error configuration:1:1
[e42e92a5b90deb7c7639a5f3ebac89d061dd5027] Testing 3 connections scripts.4ef01a59.js:2:2756
Exposed interface "/:/plugins/*/messaging" vendor.859d191d.js:20:5079
Exposed interface "" vendor.859d191d.js:20:5079
Exposed root method "details" vendor.859d191d.js:20:5395
Exposed root method "identity" vendor.859d191d.js:20:5395
"[e42e92a5b90deb7c7639a5f3ebac89d061dd5027] Testing connection: https://172-17-42-1.d0d1c17f17f144aaa03fa93d964616a9.plex.direct:32400" scripts.4ef01a59.js:2:2933
Exposed interface "/:/plugins/*/messaging" vendor.859d191d.js:20:5079
Exposed interface "" vendor.859d191d.js:20:5079
Exposed root method "details" vendor.859d191d.js:20:5395
Exposed root method "identity" vendor.859d191d.js:20:5395
"[e42e92a5b90deb7c7639a5f3ebac89d061dd5027] Testing connection: https://192-168-1-112.d0d1c17f17f144aaa03fa93d964616a9.plex.direct:32400" scripts.4ef01a59.js:2:2933
Exposed interface "/:/plugins/*/messaging" vendor.859d191d.js:20:5079
Exposed interface "" vendor.859d191d.js:20:5079
Exposed root method "details" vendor.859d191d.js:20:5395
Exposed root method "identity" vendor.859d191d.js:20:5395
"[e42e92a5b90deb7c7639a5f3ebac89d061dd5027] Testing connection: https://71-90-229-130.d0d1c17f17f144aaa03fa93d964616a9.plex.direct:19826" scripts.4ef01a59.js:2:2933
"[e42e92a5b90deb7c7639a5f3ebac89d061dd5027] Using connection: https://71-90-229-130.d0d1c17f17f144aaa03fa93d964616a9.plex.direct:19826" scripts.4ef01a59.js:2:3586
syntax error configuration:1:1
[e42e92a5b90deb7c7639a5f3ebac89d061dd5027] Request "system.ping" Object { args: Array[1], kwargs: undefined } scripts.4ef01a59.js:2:5909
Legacy response format returned scripts.4ef01a59.js:2:6173
[e42e92a5b90deb7c7639a5f3ebac89d061dd5027] Response null scripts.4ef01a59.js:2:6221
Potentially unhandled rejection [3] i.prototype.call/<@http://trakt-for-plex.github.io/configuration/scripts/scripts.4ef01a59.js:2:6267
O@http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:21905
K@http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:21539
y.prototype.when@http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:25213
v.prototype.run@http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:24247
a.prototype._drain@http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:27464
a/this.drain@http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:27131
b@http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:9721

**Comment by fuzeman** [comment]
```Legacy response format returned``` usually means the plugin is running an old version of the plugin, could you confirm what version you have installed via Plex/Web (```Channels -> trakt -> About```)?

If you aren't on v1.0.0.3, download the latest release from here: https://github.com/trakt/Plex-Trakt-Scrobbler/releases

**Comment by tillmanj** [comment]
Channels -> trakt does not load anything.

I am on 1.0.0.3 downloaded from https://github.com/trakt/Plex-Trakt-Scrobbler/releases

To make sure of that I just deleted and reinstalled the Channel. Same behavior

**Comment by fuzeman** [comment]
Could you upload the plugin log files? see https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files for the location of them.

**Comment by tillmanj** [comment]
appended .txt so it would upload

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt-for-plex/configuration/files/131520/com.plexapp.plugins.trakttv.log.txt)

**Comment by fuzeman** [comment]
It looks like the plugin is installed in the wrong directory, it should be installed at (on Synology devices):
```
/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/
```

**Comment by tillmanj** [comment]
...and it all seems to be working now. Thanks!

**Comment by chrisperra** [comment]
I'm having similar issues with the plugin, on a Drobo 5N, the configuration page just gives a HTTP 500 error. 

Log file

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt-for-plex/configuration/files/244349/com.plexapp.plugins.trakttv.log.txt)

**Comment by fuzeman** [comment]
@chrisperra Looks like the plugin isn't starting up correctly, see https://github.com/trakt/Plex-Trakt-Scrobbler/issues/303#issuecomment-208895196 for a workaround *(ignore the first step, the latest version of the plugin already includes these changes)*.

Please open a new issue at https://github.com/trakt/Plex-Trakt-Scrobbler if that workaround doesn't work.
