### ISSUE TITLE
Server Overloaded Error

### ISSUE THREAD

**Issue by dmpohlmann** [trakt-for-plex/configuration#18]
Hi 

I keep receiving the following error when attempting to sync:

ServerError: Service Unavailable - "Server Overloaded (try again in 30s)"

Is there a resolution or is this a temporary error?

Thanks,
DM

**Comment by fuzeman** [comment]
Yeah, the Trakt.tv API was down for a couple of hours. Looks like everything is working correctly now though.

**Comment by dmpohlmann** [comment]
Ok great, no problems. It does now seem to be working correctly.


On 17 June 2016 at 09:14:24, Dean Gardiner (notifications@github.com) wrote:

Yeah, the Trakt.tv API was down for a couple of hours. Looks like everything is working correctly now though.
