### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by saitoh183** [trakt-for-plex/configuration#2]
Deleting Account is not working...nothing happens when i try it on a user account

**Comment by fuzeman** [comment]
Yeah, haven't implemented this yet as it will likely cause issues in the plugin.

Need to work out the best way to delete accounts without potentially breaking rules, session history, etc..

**Comment by fuzeman** [comment]
Supported in [v1.2.0](https://github.com/trakt-for-plex/configuration/releases/tag/1.2.0) of the configuration site, and [v0.9.10.11-beta](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v0.9.10.11-beta) of the plugin.
