### ISSUE TITLE
Mark Separate user accounts in Plex from Trakt 

### ISSUE THREAD

**Issue by fleinbach** [trakt-for-plex/configuration#26]
I have 48 user accounts in Plex before I started using Trakt. On a typical day Trakt catalogs in history about 2 dozen watched shows. This is a mixture of my  4 or 5 shows I watch daily and numerous friends accounts on Plex. It would be great if Trakt marked who watched a show from the Plex accounts. Right now I see no way to determine who watched what. Is this doable at this time and if so how do I do it?

**Comment by fuzeman** [comment]
Trakt.tv accounts aren't really designed to be used by multiple users, so this isn't available now (and probably won't be implemented in the future).

If you configure each user with a separate Trakt.tv account (as described [here](https://github.com/trakt-for-plex/configuration/issues/1)) and add their accounts as friends you will see their history, ratings, etc.. on the website. If you just want to monitor the activity on your server, something like https://github.com/JonnyWong16/plexpy might be a better fit.

**Comment by fleinbach** [comment]
Thanks a million Fuzeman.  Plexpy does exactly what I was looking for and more.
