### ISSUE TITLE
"Unknown error" when trying to connect to Plex Media Server

### ISSUE THREAD

**Issue by ptirmal** [trakt-for-plex/configuration#31]
After authorizing trakt via plex.tv I am receiving an "unknown error" when trying to connect. May have something to do with plex account names that were synced to trakt that were changed in plex.

I'm on trakt plugin 1.3.1 and PMS 1.3.3.3148

**Comment by ptirmal** [comment]
Anything?

**Comment by fuzeman** [comment]
Sorry for the late response. Could you open the Browser Console *(`Ctrl + Shift + J` on Chrome, `Ctrl + Shift + K` on Firefox)* and screenshot the messages displayed after attempting another connection on the configuration site.

**Comment by ptirmal** [comment]
Here is what is displayed on firefox:

https://i.imgur.com/IC3Uk5Z.png

**Comment by ptirmal** [comment]
I was able to get access to the configuration page. I believe it was the way I was logging into plex to authenticate trakt (the pin), I was using my username, not the e-mail, and I think my e-mail was linked to trakt. I logged in via my e-mail and it works!
