### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by jaredcat** [trakt-for-plex/configuration#32]
After OAuth with my account and clicking on my server I get the error:
`Only secure servers are supported when browsing over https://`

Requests so `/identity` fail without a response either due to `net::ERR_BLOCKED_BY_CLIENT` or `net::ERR_INSECURE_RESPONSE`

My server is publicly accessible with port `32400` open but I also use a reverse proxy with an ssl cert.

Is there specific settings I need to change to get this to work?

**Comment by fuzeman** [comment]
Try http://trakt-for-plex.github.io/configuration (not `https://`). This error basically means an insecure endpoint for your server was found but you are currently using HTTPS (which will likely block the insecure server requests).

If your server *requires* secure connections, then there might be a bug with the Plex server registry (which has insecure endpoints included for some reason) or an issue with our endpoint testing system in the configuration interface.

**Comment by jaredcat** [comment]
Facepalm.
I tried that but forgot I have HTTPS Everywhere turned on.

I had to add a non-https custom server access URL and turn secure connection to "preferred" from "required".
It's weird that the identity calls to the https endpoints don't work though.

**Comment by fuzeman** [comment]
Interesting, will try do some more testing with secure server connections later this week.
