### ISSUE TITLE
Watched status not synced only scrobbling

### ISSUE THREAD

**Issue by MaartenMol96** [trakt-for-plex/configuration#4]
I seem to have a little issue. Set it up like the documentation, my own account is perfect. However, my friends accounts are scrobbling but not syncing the watched status when they just hit the mark as watched button.

I think this is a bug or am I doing something wrong?

**Comment by fuzeman** [comment]
Clicking "Mark as watched" *(in plex)* won't automatically update trakt yet *(this feature needs to be implemented again on the beta branch)*. Currently you need to manually trigger a sync for their account in ```Channels -> trakt -> Sync```.

I'm hoping to have some automatic syncing features released later this week.

**Comment by MaartenMol96** [comment]
This is not what I meant. I mean, when I do what you say, it won't set movies watched on Trakt when they are on Plex.

**Comment by fuzeman** [comment]
Ah, in that case could upload the plugin log files after running a sync, see https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files for the location of them.

The log files should give some pointers as to why syncing isn't working.
