### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by saitoh183** [trakt-for-plex/configuration#6]
![image](https://cloud.githubusercontent.com/assets/1534197/9026606/a253678e-3903-11e5-95ab-99e798ab2664.png)

Im using the latest stable...i reinstalled it also

**Comment by saitoh183** [comment]
I had to roll back to beta

**Comment by fuzeman** [comment]
This is normally only returned when you have the master branch installed.

Do you have Unsupported Appstore installed? your plugin might of rolled back to the master version automatically *(when an update was released recently)*.

**Comment by saitoh183** [comment]
Yeah.. That is what happened
