### ISSUE TITLE
Unknown Error [c838ddd82831d08d0b742e4fc4434ddf337181ff]

### ISSUE THREAD

**Issue by dachewster99** [trakt-for-plex/configuration#64]
When attempting to Login to the Trakt plugin I get the Unknown Error message, 
![image](https://user-images.githubusercontent.com/35871585/123339543-67a52000-d510-11eb-89fa-3843ea2e2fcb.png)

and this in the console
[c838ddd82831d08d0b742e4fc4434ddf337181ff] Using connection: https://192-168-1-120.aefefc72240f4e8db3ee9aa71369071f.plex.direct:32400

**Comment by jbreitbart** [comment]
I have the same problem and get a similar error message. My plex server is running in my local network, but should be accessible from the outside. Anyone got an idea how to fix this?

I have another server that has a public IPv4 address and I can configure that just fine.

**Comment by dachewster99** [comment]
i reformatted my pc, and no longer have this issue. Not sure exactly what fixed it, but i did install the c++ x86 stuff and that did allow me to login succussfully
