### ISSUE TITLE
Pin for adding plex account

### ISSUE THREAD

**Issue by saitoh183** [trakt-for-plex/configuration#9]
I was wondering how this is suppose to work?

I tried it and it just adds my account instead of the users plex account. Im guessing the user needs to be logged in to plex.tv and then use the Pin? if that is the case then i would still need to get the users password to login to plex.tv and then input his pin. 

Also on a side note , i dont know if it is relevant or not, but user switching on the web interface seems to be broken and i (and others on the forum) are unable to enter other user accounts that are part of our plex home. I works with The Android app and roku and windows 8.1 app but not in the browser.

**Comment by saitoh183** [comment]
https://support.plex.tv/hc/en-us/articles/203815766-What-is-Plex-Home-

it seems they removed the function so fast switching will require the pin if there is one for the account. Will this cause a problem for configuring new users?

**Comment by fuzeman** [comment]
> I was wondering how this is suppose to work?

> I tried it and it just adds my account instead of the users plex account. Im guessing the user needs to be logged in to plex.tv and then use the Pin? if that is the case then i would still need to get the users password to login to plex.tv and then input his pin. 

Plex PIN authentication was added as entering your plex username/password on a third-party website probably doesn't feel that safe.

You could ask them to open https://plex.tv/pin and enter the pin on their computer, this might work? *(haven't tested it, PINs could be locked to your IP Address)*

> it seems they removed the function so fast switching will require the pin if there is one for the account. Will this cause a problem for configuring new users?

Well, it would mean you would have to either:
 - Ask them for the user switching pin
 - Ask them to remove the user switching pin while you setup their account

This probably isn't a big limitation, it just needs to be documented properly to ensure everyone understands how this works.

**Comment by saitoh183** [comment]
gotcha :)
